### ISSUE TITLE
Not possible to add a new yeswiki in same domain than previous one

### ISSUE THREAD

**Issue by J9rem** [YunoHost-Apps/yeswiki_ynh#47] opened 2022-01-24 19:45 UTC
### Describe the bug

When using application management interface of Yunohost and trying to add YesWiki application on the same domain of a previous one install, but with a different path, there is a message that said that the path is already used (see detail below).

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin| ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no *

### Steps to reproduce

- Using, or trying to install package version/branch: YesWiki 2022-01-16-13~ynh1

 - wanted path `https://www.example.com/yeswiki2`
 - previous path `https://www.example.com/yeswiki` (for the previous yeswiki already working)
 - error saying that  `https://www.example.com/yeswiki` is already used (normal but I asked `https://www.example.com/yeswiki2`)

### Expected behavior

No error expected

**Comment by J9rem** [comment] 2022-01-24 19:46
@mrflos do you have an idea on this ?

**Comment by mrflos** [comment] 2022-01-25 07:15
No, I checked wordpress or mediawiki app, and they do the same...  
ping @alexAubin or @ericgaspar : is `$YNH_APP_INSTANCE_NAME` not making an unique id for the app? Do we have something non-standard in https://github.com/YunoHost-Apps/yeswiki_ynh/blob/master/scripts/install ? thx!!

**Comment by alexAubin** [comment] 2022-01-25 11:51
>wanted path https://www.example.com/yeswiki2
>
>previous path https://www.example.com/yeswiki (for the previous yeswiki already working)
>
>error saying that https://www.example.com/yeswiki is already used (normal but I asked https://www.example.com/yeswiki2)


This is the "expected" behavior ... because one path starts by the other (yeswiki2 starts by yeswiki) .... Or at least, that's the behavior since I'm in the project ... I assumed that somehow there was a reason for this to prevent some weird conflict, but nowadays I can probably confidently say that this is indeed bullshit and this should be perfectly fine ...

Anyway, that's not a bug in yeswiki, this is a core issue

**Comment by mrflos** [comment] 2022-01-25 12:20
Ok, thanks for your quick answer @alexAubin <3 !
All path names should have different prefixes, good to know!  

Do you want me to open an issue in https://github.com/YunoHost/issues/issues and close this one?

**Comment by alexAubin** [comment] 2022-01-25 12:48
Yes it can be good to keep track of it :+1:

**Comment by mrflos** [comment] 2022-01-25 13:02
Done, bisous!

**Closed by mrflos** 2022-01-25 13:02 UTC
